version: 2
updates: 
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    target-branch: "main"
    labels:
      - "kind/dependencies"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    target-branch: "main"
    labels:
      - "kind/dependencies"
    ignore:
      - dependency-name: "wasmtime"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
  # Add entries for excluded workspace members
  - package-ecosystem: "cargo"
    directory: "/src/wasm_runtime"
    schedule:
      interval: "daily"
      time: "03:00"
    target-branch: "main"
    labels:
      - "kind/dependencies"
    ignore:
      - dependency-name: "wasmtime"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
  - package-ecosystem: "cargo"
    directory: "/src/rust_wasm_samples"
    schedule:
      interval: "daily"
      time: "03:00"
    target-branch: "main"
    labels:
      - "kind/dependencies"
  - package-ecosystem: "cargo"
    directory: "/src/hyperlight_wasm_macro"
    schedule:
      interval: "daily"
      time: "03:00"
    target-branch: "main"
    labels:
      - "kind/dependencies"
  - package-ecosystem: "cargo"
    directory: "/src/component_sample"
    schedule:
      interval: "daily"
      time: "03:00"
    target-branch: "main"
    labels:
      - "kind/dependencies"
