// Generated by `wit-bindgen` 0.38.0. DO NOT EDIT!
#ifndef __BINDINGS_RUNCOMPONENT_H
#define __BINDINGS_RUNCOMPONENT_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct runcomponent_string_t {
  uint8_t*ptr;
  size_t len;
} runcomponent_string_t;

// Imported Functions from `example:runcomponent/host`
extern int64_t example_runcomponent_host_get_time_since_boot_microsecond(void);

// Exported Functions from `example:runcomponent/guest`
void exports_example_runcomponent_guest_echo(runcomponent_string_t *msg, runcomponent_string_t *ret);

// Helper Functions

// Transfers ownership of `s` into the string `ret`
void runcomponent_string_set(runcomponent_string_t *ret, const char*s);

// Creates a copy of the input nul-terminate string `s` and
// stores it into the component model string `ret`.
void runcomponent_string_dup(runcomponent_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void runcomponent_string_free(runcomponent_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
