package example:runcomponent;

interface guest {
    echo: func(msg: string) -> string;
    round-to-nearest-int: func(a: f32, b: f32) -> s32;
}

interface host {
    get-time-since-boot-microsecond: func() -> s64;
}

world runcomponent {
    export guest;
    import host;
}