// Generated by `wit-bindgen` 0.43.0. DO NOT EDIT!
#include "runcomponent.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `example:runcomponent/host`

__attribute__((__import_module__("example:runcomponent/host"), __import_name__("get-time-since-boot-microsecond")))
extern int64_t __wasm_import_example_runcomponent_host_get_time_since_boot_microsecond(void);

// Exported Functions from `example:runcomponent/guest`

__attribute__((__weak__, __export_name__("cabi_post_example:runcomponent/guest#echo")))
void __wasm_export_exports_example_runcomponent_guest_echo_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}


// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(sizeof(void*))))
static uint8_t RET_AREA[(2*sizeof(void*))];

// Helper Functions

void runcomponent_string_set(runcomponent_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void runcomponent_string_dup(runcomponent_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void runcomponent_string_free(runcomponent_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

int64_t example_runcomponent_host_get_time_since_boot_microsecond(void) {
  int64_t ret = __wasm_import_example_runcomponent_host_get_time_since_boot_microsecond();
  return ret;
}

__attribute__((__export_name__("example:runcomponent/guest#echo")))
uint8_t * __wasm_export_exports_example_runcomponent_guest_echo(uint8_t * arg, size_t arg0) {
  runcomponent_string_t arg1 = (runcomponent_string_t) { (uint8_t*)(arg), (arg0) };
  runcomponent_string_t ret;
  exports_example_runcomponent_guest_echo(&arg1, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("example:runcomponent/guest#round-to-nearest-int")))
int32_t __wasm_export_exports_example_runcomponent_guest_round_to_nearest_int(float arg, float arg0) {
  int32_t ret = exports_example_runcomponent_guest_round_to_nearest_int(arg, arg0);
  return ret;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_runcomponent(void);
void __component_type_object_force_link_runcomponent_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_runcomponent();
}
