# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# When a new Tag with the prefix v is pushed to the repository, this workflow will create a new release branch called release/<tag name>. 

name: Create a Release Branch

on:
  push:
    tags: 
      - 'v*'

permissions:
  contents: write # Needed to push new branch

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: extractions/setup-just@v3
      with:
        just-version: "1.40"
    - name: Create Release Branch
      run: |
        git checkout -b release/${GITHUB_REF_NAME}
        just make-vendor-tar
        sed '/vendor.tar/d' ./src/hyperlight_wasm/.gitignore
        git add ./src/hyperlight_wasm/vendor.tar
        git add ./src/hyperlight_wasm/.gitignore
        git commit -m "Vendor dependencies for release ${GITHUB_REF_NAME}" -s -S
        git push --set-upstream origin release/${GITHUB_REF_NAME}
      shell: bash
